import 'package:flutter/material.dart';
import '../../features/recipe_generator/recipe_detail_screen.dart';

/// DietCompass — AI Meal Plan Models
///
/// Encapsulates multi-day personalized meal plans generated by the backend.

class MealPlanMeal {
  final String type;
  final String recipeId;
  final String title;
  final String description;
  final int calories;
  final int proteinGrams;
  final int carbsGrams;
  final int fatGrams;
  final int fiberGrams;
  final String image;
  final List<String> ingredients;
  final List<String> instructions;
  final bool isVegetarian;

  const MealPlanMeal({
    required this.type,
    required this.recipeId,
    required this.title,
    this.description = '',
    required this.calories,
    required this.proteinGrams,
    this.carbsGrams = 45,
    this.fatGrams = 10,
    this.fiberGrams = 5,
    required this.image,
    this.ingredients = const [],
    this.instructions = const [],
    this.isVegetarian = true,
  });

  factory MealPlanMeal.fromJson(Map<String, dynamic> json) {
    final ingsRaw = json['ingredients'] as List?;
    final ingredients = (ingsRaw != null)
        ? ingsRaw.map((e) => e.toString()).toList()
        : <String>[];

    final instRaw = json['instructions'] as List?;
    final instructions = (instRaw != null)
        ? instRaw.map((e) => e.toString()).toList()
        : <String>[];

    return MealPlanMeal(
      type: json['type']?.toString() ?? 'Meal',
      recipeId: json['recipeId']?.toString() ?? json['id']?.toString() ?? '',
      title: json['title']?.toString() ?? 'Delicious Recipe',
      description: json['description']?.toString() ?? '',
      calories: (json['calories'] as num?)?.toInt() ?? (json['kcal'] as num?)?.toInt() ?? 350,
      proteinGrams: (json['proteinGrams'] as num?)?.toInt() ?? (json['protein'] as num?)?.toInt() ?? 12,
      carbsGrams: (json['carbsGrams'] as num?)?.toInt() ?? (json['carbs'] as num?)?.toInt() ?? 45,
      fatGrams: (json['fatGrams'] as num?)?.toInt() ?? (json['fat'] as num?)?.toInt() ?? 10,
      fiberGrams: (json['fiberGrams'] as num?)?.toInt() ?? (json['fiber'] as num?)?.toInt() ?? 5,
      image: json['image']?.toString() ?? json['imageUrl']?.toString() ?? json['imageAsset']?.toString() ?? '',
      ingredients: ingredients,
      instructions: instructions,
      isVegetarian: json['isVegetarian'] != false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'type': type,
      'recipeId': recipeId,
      'title': title,
      'description': description,
      'calories': calories,
      'proteinGrams': proteinGrams,
      'carbsGrams': carbsGrams,
      'fatGrams': fatGrams,
      'fiberGrams': fiberGrams,
      'image': image,
      'ingredients': ingredients,
      'instructions': instructions,
      'isVegetarian': isVegetarian,
    };
  }

  Recipe toRecipe() {
    final defaultImage = image.isNotEmpty ? image : '';
    final nutritionFacts = <NutritionFact>[
      NutritionFact(
        icon: Icons.local_fire_department,
        color: const Color(0xFFE0862E),
        label: 'Calories',
        value: '$calories\nkcal',
      ),
      NutritionFact(
        icon: Icons.circle,
        color: const Color(0xFF6C4EF5),
        label: 'Carbs',
        value: '${carbsGrams}g',
      ),
      NutritionFact(
        icon: Icons.eco,
        color: const Color(0xFF1E8A4C),
        label: 'Protein',
        value: '${proteinGrams}g',
      ),
      NutritionFact(
        icon: Icons.opacity,
        color: const Color(0xFFE0B32E),
        label: 'Fat',
        value: '${fatGrams}g',
      ),
    ];

    final ingredientItems = ingredients.isNotEmpty
        ? ingredients.map((i) => IngredientItem(amount: '1 portion', name: i)).toList()
        : [IngredientItem(amount: '1 portion', name: title)];

    final recipeInstructions = instructions.isNotEmpty
        ? instructions
        : const [
            'Prepare all fresh ingredients.',
            'Combine and cook according to recipe instructions.',
            'Serve warm and enjoy your healthy meal!',
          ];

    return Recipe(
      id: recipeId.isNotEmpty ? recipeId : title.toLowerCase().replaceAll(' ', '_'),
      images: defaultImage.isNotEmpty ? [defaultImage] : [],
      title: title,
      tags: [type, isVegetarian ? 'Vegetarian' : 'Non-Vegetarian', 'Healthy'],
      description: description.isNotEmpty ? description : 'Delicious and wholesome recipe tailored for your meal plan.',
      prepTime: '20 mins',
      calories: '$calories kcal',
      protein: '${proteinGrams}g',
      difficulty: 'Easy',
      nutritionFacts: nutritionFacts,
      ingredients: ingredientItems,
      serves: 2,
      instructions: recipeInstructions,
    );
  }
}

class MealPlanDay {
  final int day;
  final String dayLabel;
  final String dayNumber;
  final String date;
  final List<MealPlanMeal> meals;
  final int dailyCalories;
  final int dailyProtein;
  final int dailyFiber;
  final int waterGlasses;

  const MealPlanDay({
    required this.day,
    required this.dayLabel,
    required this.dayNumber,
    required this.date,
    required this.meals,
    required this.dailyCalories,
    required this.dailyProtein,
    required this.dailyFiber,
    this.waterGlasses = 8,
  });

  factory MealPlanDay.fromJson(Map<String, dynamic> json) {
    final rawMeals = json['meals'] as List?;
    final meals = (rawMeals != null)
        ? rawMeals
            .whereType<Map<String, dynamic>>()
            .map((m) => MealPlanMeal.fromJson(m))
            .toList()
        : <MealPlanMeal>[];

    return MealPlanDay(
      day: (json['day'] as num?)?.toInt() ?? 1,
      dayLabel: json['dayLabel']?.toString() ?? 'Mon',
      dayNumber: json['dayNumber']?.toString() ?? 'Day 1',
      date: json['date']?.toString() ?? '',
      meals: meals,
      dailyCalories: (json['dailyCalories'] as num?)?.toInt() ?? 1800,
      dailyProtein: (json['dailyProtein'] as num?)?.toInt() ?? 70,
      dailyFiber: (json['dailyFiber'] as num?)?.toInt() ?? 28,
      waterGlasses: (json['waterGlasses'] as num?)?.toInt() ?? 8,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'day': day,
      'dayLabel': dayLabel,
      'dayNumber': dayNumber,
      'date': date,
      'meals': meals.map((m) => m.toJson()).toList(),
      'dailyCalories': dailyCalories,
      'dailyProtein': dailyProtein,
      'dailyFiber': dailyFiber,
      'waterGlasses': waterGlasses,
    };
  }
}

class MealPlanTotals {
  final int averageCalories;
  final int averageProtein;
  final int averageFiber;

  const MealPlanTotals({
    required this.averageCalories,
    required this.averageProtein,
    required this.averageFiber,
  });

  factory MealPlanTotals.fromJson(Map<String, dynamic> json) {
    return MealPlanTotals(
      averageCalories: (json['averageCalories'] as num?)?.toInt() ?? 1800,
      averageProtein: (json['averageProtein'] as num?)?.toInt() ?? 70,
      averageFiber: (json['averageFiber'] as num?)?.toInt() ?? 28,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'averageCalories': averageCalories,
      'averageProtein': averageProtein,
      'averageFiber': averageFiber,
    };
  }
}

class MealPlanResponse {
  final int durationDays;
  final String goal;
  final String diet;
  final int targetCalories;
  final String summary;
  final bool geminiPowered;
  final List<MealPlanDay> days;
  final MealPlanTotals totals;

  const MealPlanResponse({
    required this.durationDays,
    required this.goal,
    required this.diet,
    required this.targetCalories,
    required this.summary,
    this.geminiPowered = false,
    required this.days,
    required this.totals,
  });

  factory MealPlanResponse.fromJson(Map<String, dynamic> json) {
    final rawDays = json['days'] as List?;
    final days = (rawDays != null)
        ? rawDays
            .whereType<Map<String, dynamic>>()
            .map((d) => MealPlanDay.fromJson(d))
            .toList()
        : <MealPlanDay>[];

    final totalsMap = json['totals'] as Map<String, dynamic>?;

    return MealPlanResponse(
      durationDays: (json['durationDays'] as num?)?.toInt() ?? days.length,
      goal: json['goal']?.toString() ?? 'Weight Loss',
      diet: json['diet']?.toString() ?? 'Vegetarian',
      targetCalories: (json['targetCalories'] as num?)?.toInt() ?? 1800,
      summary: json['summary']?.toString() ?? 'Personalized AI Meal Plan tailored for your dietary goals.',
      geminiPowered: json['geminiPowered'] == true,
      days: days,
      totals: totalsMap != null
          ? MealPlanTotals.fromJson(totalsMap)
          : const MealPlanTotals(averageCalories: 1800, averageProtein: 70, averageFiber: 28),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'durationDays': durationDays,
      'goal': goal,
      'diet': diet,
      'targetCalories': targetCalories,
      'summary': summary,
      'geminiPowered': geminiPowered,
      'days': days.map((d) => d.toJson()).toList(),
      'totals': totals.toJson(),
    };
  }
}
